### PR TITLE
Add custom branding examples and documentation for creating new themes

### PR DESCRIPTION
**Pull request by VoxSecundus**
- Created two basic 'themes' under `/landing-page/types` (`red-theme`, `green-theme`)
- Added documentation on how to create/apply new themes

### CODE REVIEW

**Comment by benarmston** [comment]
I've added a commit that changes the red theme so that the blue clashes with the red a little less.  It now looks like this:

image

**Comment by benarmston** [comment]
There are a couple of minor issues with the green theme that I'd like addressed.  The nav and footer have an odd coloured border and there is some black on dark green text which is not readily readable.

image

---

The theme instructions are a good first stab and they work well for themeing a manual installation.   However they are not quite right when themeing the landing page installed from an RPM.  Could you attempt to follow them for the landing page installation routed at `/opt/flight/opt/www/landing-page` and make any needed changes to the instructions.

**Comment by VoxSecundus** [comment]
Understood. I've also noticed that my instructions on how to create a symbolic link are wrong; not using an absolute path for the linked file results in pathing errors.

**Comment by benarmston** [comment]
Thanks for making those changes @VoxSecundus.  I've made a couple of changes to the themes to document how to add a sub brand header; "Red theme" in the picture below.

image

I've also reworked the branding / theme documentation to cover more use cases.  The work you did on the initial draft was a really good starting point.  Thanks.

**Pull request merged**
